apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arca
  namespace: arca
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: admin.arca.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arca-web
                port:
                  number: 80
    - host: api.arca.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arca-api
                port:
                  number: 80
